### ISSUE TITLE
[Coverage] Return Result on Finish

### ISSUE THREAD

**Issue by petems** [rodjek/rspec-puppet#178]
Would be cool if the coverage task returned a value when finished, so you could do some sort of Rake task that exits 1 if coverage is not 100% or some other arbitrary value :+1:

**Comment by logicminds** [comment]
This would not really work since your unit tests would only cover a subset of the resources that might actually be in the catalog.  For example, if your class requires some other class that is outside your module, you would fail the test since your not testing the other module code as well. Now if puppet-rspec scoped only the classes/defines that are contained in the unit test and never showed all the other resources that don't have a unit tests than this might be useful.

**Comment by DavidS** [comment]
This is related to #162 and #158

**Comment by rodjek** [comment]
Coverage reports take a minimum coverage percent argument which causes the rspec run to fail if not met, so I believe that covers this request.
