### ISSUE TITLE
Puppet.settings[:strict_variables]=true does not work anymore since 2.2

### ISSUE THREAD

**Issue by mcanevet** [rodjek/rspec-puppet#307]
I used to enable `strict_variables` with `Puppet.settings[:strict_variables]=true` but since rspec-puppet 2.2 I have to use `c.strict_variables = true`.

**Comment by DavidS** [comment]
Hmm, [setup_puppet](https://github.com/rodjek/rspec-puppet/blob/6c0bc76d7ef0847b519cba04d8b530c47573cd23/lib/rspec-puppet/support.rb#L129) called at https://github.com/rodjek/rspec-puppet/blob/6c0bc76d7ef0847b519cba04d8b530c47573cd23/lib/rspec-puppet/support.rb#L15 and https://github.com/rodjek/rspec-puppet/blob/ee85f33a47a671207f0c88713e1c82a55c096081/lib/rspec-puppet/example/function_example_group.rb#L10 configures puppet as a side effect of setting up the subject.

 The alternatives I see are pulling the setup_puppet call into a earlier phase, like add it after https://github.com/rodjek/rspec-puppet/blob/6c0bc76d7ef0847b519cba04d8b530c47573cd23/lib/rspec-puppet.rb#L55 ; that way the settings can be overwritten on a test-by-test basis or just improving the docs around this.

I feel calling setup_puppet earlier would be preferable, but it might destabilise the situation even more. Calling for opinions here. @igalic, @hunner , @duritong @electrical  @daenney  @nibalizer ?

**Comment by nibalizer** [comment]
I have no opinion.

**Comment by daenney** [comment]
`Puppet.settings[:strict_variables]=true` afaik was needed because we had no switch on `rspec-puppet` itself to enable it, contrary to many of the other settings that you could toggle through `rspec-puppet` that would affect this.

I'd say we should pick one method or the other, not both. So as far as I'm concerned I'd like to actually rip out the code that allows you to toggle Puppet settings through `config.$puppet_option=value` and teach people to use `Puppet.settings[$puppet_option]=value`. It keeps everything in one place and makes it nice and obvious as to what settings we're toggling where.

**Comment by duritong** [comment]
I support @daenney's suggestion.

**Comment by electrical** [comment]
Using Puppet.settings makes more sense since it will support any settings that may come or go without having to patch rspec-puppet every time.

**Comment by jhoblitt** [comment]
:+1:  for @daenney 's suggestion as long as its a major version bump.

**Comment by DavidS** [comment]
So people would rather use Puppet.settings directly, to avoid having to change rspec-puppet for new config vars and for clarity when what happens.

On the other hand, puppet complains loudly (exception) when config values not applicable to the current version are set, and I don't like to force people to hand-code if PUPPETVERSION things in their spec_helpers.

A compromise solution would be to have a version-independent config-setter that swallows the error. Meh.

**Comment by daenney** [comment]
I think we can swallow the error and still emit a notification to the end user though so that they can clearly see what happens. There's no need to swallow and hide this thing entirely.

```
The option :strict_variables is not a valid option for Puppet version: #{PUPPETVERSION} and will have no effect on this run
The option :....
```

**Comment by DavidS** [comment]
True that, @daenney .

Adding a new function also doesn't need a major version bump.

**Comment by igalic** [comment]
what @daenney said.

**Comment by rodjek** [comment]
A bit of thread necromancy here, but y'know.

The reason I always preferred having the abstraction in front of the settings was so that rspec-puppet could reset the settings back after each test. If we moved to just telling people to use `Puppet.settings[:whatever] = value` then we'd lose this and users would have to remember to change the settings back in their own `after` hook (if they changed them).

As a possible middleground, what if we change the way that the settings are set so that values set in `RSpec.configure` override the application default values instead of setting the value itself? That way if you want to use `Puppet.settings[]`, they'll take preference over the values from `RSpec.configure` (though as mentioned before, they won't be reset between tests, so you'll have to handle that yourself).

**Comment by daenney** [comment]
> As a possible middleground, what if we change the way that the settings are set so that values set in RSpec.configure override the application default values instead of setting the value itself? That way if you want to use Puppet.settings[], they'll take preference over the values from RSpec.configure (though as mentioned before, they won't be reset between tests, so you'll have to handle that yourself).

I like it. :shipit:
