### ISSUE TITLE
contain_class('::mymodule') doesn't work whereas contain_class('mymodule') does

### ISSUE THREAD

**Issue by j-vizcaino** [rodjek/rspec-puppet#312]
Howto reproduce:

`manifests/init.pp`:

```puppet
class mymodule { }
```

`spec/classes/init_spec.rb`:

```ruby
require 'spec_helper'
describe 'mymodule' do

  context 'with default parameters' do
    it {
      should contain_class('mymodule')
      should contain_class('::mymodule')
    }
  end

end
```

I would expect this to work, because in this context Puppet considers `Class[mymodule]` and `Class[::mymodule]` to have the same meaning.

rspec-puppet version used: 2.2.0

**Comment by DavidS** [comment]
Apologies for the late notice, but I only realized now that this is caused by rspec-puppet not having/doing scope lookups like the full puppet parser. I've added a note about that to the README (https://github.com/rodjek/rspec-puppet/pull/339/files#diff-04c6e90faac2675aa89e2176d2eec7d8R114) , but pending someone actually implementing the parsing logic, it will not be addressed.
