### ISSUE TITLE
2.6.3 is not setting environment.manifest any longer

### ISSUE THREAD

**Issue by trevor-vaughan** [rodjek/rspec-puppet#556]
In `2.5.0`, `environment.manifest` was set to `spec/fixtures/manifests` by default and showed as such when used by the Puppet modules.

As far as I can tell, this is supposed to *always* be set when Puppet compiles.

With `2.6.0`, this is being set to the **Symbol** `:no_manifest` at run time and causing issues with my tests since I use the `environment.manifest` information in some functions.

I would like to request that this behavior be reverted until `3.0.0`.

**Comment by trevor-vaughan** [comment]
Did some additional checking and it looks like we only have the one module that was using this and it probably won't affect most users. That said, it is a breaking change in behavior but may be more correct than it used to be (I'm not sure).

**Comment by trevor-vaughan** [comment]
@rodjek As an addition to this, the following code now throws an error stating `Unsupported data type: 'Symbol'`.

```
let(:environment) {:production}
```

Changing `:production` to a String fixes this but it's still a breaking change against `2.5.0`.

**Comment by rodjek** [comment]
@trevor-vaughan I've opened a PR to address the environment as a symbol issue.

In regards to `environment.manifest` not being set, as you said this is a bit of an edge case, so could you create a small test repo that reproduces the problem (or if the module you are referencing is public, send me a link to it) so that I can investigate further?

**Comment by trevor-vaughan** [comment]
@rodjek Here's where we're using it https://github.com/simp/pupmod-simp-compliance_markup/blob/master/lib/puppet/parser/functions/compliance_map.rb#L356. Also, thanks for staying on top of these!

**Comment by rodjek** [comment]
Thanks, I see the problem now.

`environmentpath` is an unusual setting in that it is the one setting that `Puppet::Test::TestHelper` forcefully modifies (it's even overriding where you set `environmentpath` in your spec_helper.rb). Because of the changes I made in #502 to prevent rspec-puppet from clobbering user specified settings, `Puppet::Test::TestHelper` is now setting `environmentpath` to a temp dir which is why `environment.manifest` is not being set.

I'm going to add a special case for `environmentpath` so that we can override what `Puppet::Test::TestHelper` is doing here, which will fix this up for you.

**Comment by rodjek** [comment]
2.6.4 has been pushed to rubygems with these fixes
