### ISSUE TITLE
Symlink to modules under fixtures

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#607]
In respect to this error: `spec/fixtures/modules/mymodule already exists and is not a symlink`...

I created a symlink from `spec/fixtures/modules` to the modules dir and that's i think why I'm getting the error.

If I create a dir under `spec/fixtures` and then create symlinks to individual modules from within that dir, the error goes away. 

Obviously, that warning is there for a reason. What's the best symlinking practice with rspec-puppet and why?

**Comment by rodjek** [comment]
> I created a symlink from spec/fixtures/modules to the modules dir and that's i think why I'm getting the error.

Is this a control repository or an individual module?

**Comment by gerases** [comment]
It's a control repo

**Comment by rodjek** [comment]
Generally, it's not necessary to create the fixtures symlinks for a control repo as the directory structure is already laid out (which is why rspec-puppet-init doesn't create the symlinks when run in a control repo). All you should need to do is set `module_dir` in your `spec_helper.rb` to your modules directory.
