### ISSUE TITLE
Mocking module variables

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#679]
Hi,

Usually I can fake a variable by using `facts`, but in this case the puppet code has a condition of the form:

```
if ($SOME_MODULE:SOME_VAR == true) {
...
```

I've tried to use:

```
    let(:pre_condition) do
      [ '$SOME_MODULE:SOME_VAR = true', ]
    end
```

but I'm getting this error: `Cannot assign to variables in other namespaces`

Is there a workaround for this problem?

Thanks much -- rspec-puppet rules.

Sergei

**Comment by rodjek** [comment]
My general recommendation is if the class you're testing has a hard dependency on another class (as in your situation), either include the required class in the class being tested or move that variable into a parameter so that it can default to `$some_module::some_var` but also be overridden.

If you can't do that refactoring though, try the following to create a dummy class to hold the stubbed variable.

```ruby
let(:pre_condition) do
  <<-EOF
    class some_module(
      $some_var = true,
    ) {}
    include some_module
  EOF
end
```

**Comment by gerases** [comment]
@rodjek Thank you so much for your answer. I'm good to go!

**Comment by rodjek** [comment]
Awesome, glad to hear it :)
